@host=http://localhost:3000/products

GET {{ host }} HTTP/1.1
###

GET {{ host }}/1 HTTP/1.1
###

POST {{ host }} HTTP/1.1
Content-Type: application/json

{
    "name": "Producto 2",
    "price": 5.20
}
###

PATCH {{ host }}/2 HTTP/1.1
Content-Type: application/json

{
    "name": "Galletas Soda Field",
    "price": 3.50
}
###

DELETE {{ host }}/1 HTTP/1.1